### ISSUE TITLE
Error bumping version not consisting of three parts

### ISSUE THREAD

**Issue by inirudebwoy** [inirudebwoy/bamp#1]
Can't bamp versions not having all the parts (major, minor, patch)

```
± % python bamp/main.py patch --current_version 1.2                            
Traceback (most recent call last):
  File "bamp/main.py", line 17, in <module>
    main()
  File "/home/majki/.virtualenvs/bamp/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/majki/.virtualenvs/bamp/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/majki/.virtualenvs/bamp/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/majki/.virtualenvs/bamp/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "bamp/main.py", line 13, in main
    print(bamp_version(current_version, part))
  File "/home/majki/projects/bamp/bamp/engine.py", line 69, in bamp_version
    version = split_version(version)
  File "/home/majki/projects/bamp/bamp/engine.py", line 29, in split_version
    return SplitVersion(*int_list)
TypeError: __new__() takes exactly 4 arguments (3 given)

```

**Comment by inirudebwoy** [comment]
Done
